bootstrap:
  parents: 1
  children: 10
  timeout: 1000
  backlog: 128
  nodelay: "true"
  keepAlive: "true"

server:
  host: "localhost"
  port: 8081

executor:
  corePoolSize: 4
  delay: 2000

chat:
  clients: 3
  messages: 10

frame:
  length: 80960